# Site settings
title: shino
description: 'shino.space - shino 的个人网站'
url: 'https://shino.space'
baseurl: '/'
google_analytics: 'UA-78168136-1'

author:
  name: 'shino'
  email: shino@shino.space
  twitter_username: shino_996
  github_username: q852217956
  qq: 852217956

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  input: kramdown
  syntax_hghlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
